In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Nhóm 7/Đồ án môn học/DATA_TRAINING/FINAL_DATASET.csv')
df.head()
#gioitinh, hedt

mssv  hocky  namhoc  diem_hp  \
0  0000AC05XPvAibaEXe9B2tolTZ0JLoBGbkQixQS6      1    2021      8.6   
1  0000AC05XPvAibaEXe9B2tolTZ0JLoBGbkQixQS6      1    2021      7.2   
2  0000AC05XPvAibaEXe9B2tolTZ0JLoBGbkQixQS6      1    2021      7.6   
3  0000AC05XPvAibaEXe9B2tolTZ0JLoBGbkQixQS6      1    2021      8.5   
4  0000AC05XPvAibaEXe9B2tolTZ0JLoBGbkQixQS6      1    2021      7.4   

   trangthai  tinhtrang   drl  dtbhk  sotchk    diem_tt  namsinh gioitinh  \
0          1          0  93.0   7.79      17  24.300111     1998      Nam   
1          1          0  93.0   7.79      17  24.300111     1998      Nam   
2          1          0  93.0   7.79      17  24.300111     1998      Nam   
3          1          0  93.0   7.79      17  24.300111     1998      Nam   
4          1          0  93.0   7.79      17  24.300111     1998      Nam   

   hedt  khoahoc  dtb_toankhoa  dtb_tichluy  sotc_tichluy  dtbhk_tt  
0  Cqui       16          7.91         7.91            62      8.28  
1  Cqui       16          7.91         7.91            62      8.28  
2  Cqui       16          7.91         7.91            62      8.28  
3  Cqui       16          7.91         7.91            62      8.28  
4  Cqui       16          7.91         7.91            62      8.28

In [ ]:
print(df['gioitinh'].unique())

['Nam']


In [ ]:
# print(df['hedt'].unique())
# 0 1 2 3 4 5

In [ ]:
df['hedt'] = df['hedt'].map({
    'Cqui': 0,
    'Clc': 1,
    'Kstn': 2,
    'Cttt': 3,
    'Cntn': 4
})

df['gioitinh'] = df['gioitinh'].map({
    'Nam': 0,
})

# Calculate the minimum values for 'namhoc' and 'namsinh'
min_namhoc = df['namhoc'].min()
min_namsinh = df['namsinh'].min()
print(min_namhoc)
print(min_namsinh)


# Subtract the minimum values from the respective columns
df['namhoc'] = df['namhoc'] - min_namhoc + 1
df['namsinh'] = df['namsinh'] - min_namsinh + 1

df.head()

2013
1985


mssv  hocky  namhoc  diem_hp  \
0  0000AC05XPvAibaEXe9B2tolTZ0JLoBGbkQixQS6      1       9      8.6   
1  0000AC05XPvAibaEXe9B2tolTZ0JLoBGbkQixQS6      1       9      7.2   
2  0000AC05XPvAibaEXe9B2tolTZ0JLoBGbkQixQS6      1       9      7.6   
3  0000AC05XPvAibaEXe9B2tolTZ0JLoBGbkQixQS6      1       9      8.5   
4  0000AC05XPvAibaEXe9B2tolTZ0JLoBGbkQixQS6      1       9      7.4   

   trangthai  tinhtrang   drl  dtbhk  sotchk    diem_tt  namsinh  gioitinh  \
0          1          0  93.0   7.79      17  24.300111       14         0   
1          1          0  93.0   7.79      17  24.300111       14         0   
2          1          0  93.0   7.79      17  24.300111       14         0   
3          1          0  93.0   7.79      17  24.300111       14         0   
4          1          0  93.0   7.79      17  24.300111       14         0   

   hedt  khoahoc  dtb_toankhoa  dtb_tichluy  sotc_tichluy  dtbhk_tt  
0     0       16          7.91         7.91            62      8.28  
1     0       16          7.91         7.91            62      8.28  
2     0       16          7.91         7.91            62      8.28  
3     0       16          7.91         7.91            62      8.28  
4     0       16          7.91         7.91            62      8.28

In [ ]:
!pip install tab-transformer-pytorch
!pip install pytorch_tabnet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.5/44.5 kB 2.6 MB/s eta 0:00:00


# **TRAINING**

In [ ]:
from sklearn.model_selection import train_test_split
import torch
from tab_transformer_pytorch import FTTransformer
import pandas as pd
import numpy as np

In [ ]:
X = df.drop(columns=['mssv', 'dtbhk_tt'])
y = df['dtbhk_tt']

In [ ]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [ ]:
categorical_columns = ['trangthai', 'gioitinh']
numerical_columns = ['diem_hp', 'drl', 'dtbhk', 'sotchk', 'diem_tt', 'dtb_toankhoa', 'dtb_tichluy', 'sotc_tichluy', 'namsinh', 'namhoc', 'hocky']

In [ ]:
print(df['trangthai'].unique())

[1 4 2 3 0 5]


In [ ]:
# print(x_train_categ[0])
# print(x_train_numer[0])

tensor([1, 0])
tensor([  9.1000,  90.0000,   8.0300,  19.0000,  23.8500,   7.9100,   7.9100,
        136.0000,  17.0000,   7.0000,   1.0000])


In [ ]:
def prepare_data(X, categorical_columns, numerical_columns):
    X_categ = X[categorical_columns].values
    X_numer = X[numerical_columns].values

    categorical_dims = [X[col].nunique() for col in categorical_columns]

    x_categ = torch.tensor(X_categ, dtype=torch.long)
    x_numer = torch.tensor(X_numer, dtype=torch.float32)

    return x_categ, x_numer, categorical_dims

In [ ]:
x_train_categ, x_train_numer, categorical_dims = prepare_data(X_train, categorical_columns, numerical_columns)
y_train_tensor = torch.tensor(y_train.values.reshape(-1, 1), dtype=torch.float32)

In [ ]:
x_val_categ, x_val_numer, _ = prepare_data(X_val, categorical_columns, numerical_columns)
y_val_tensor = torch.tensor(y_val.values.reshape(-1, 1), dtype=torch.float32)

In [ ]:
x_test_categ, x_test_numer, _ = prepare_data(X_test, categorical_columns, numerical_columns)
y_test_tensor = torch.tensor(y_test.values.reshape(-1, 1), dtype=torch.float32)

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


In [ ]:
ft_transformer_model = FTTransformer(
    categories=categorical_dims,
    num_continuous=len(numerical_columns),
    dim=8,
    dim_out=1,
    depth=6,
    heads=8,
    attn_dropout=0.1,
    ff_dropout=0.1
).to(device)
optimizer = torch.optim.Adam(ft_transformer_model.parameters(), lr=1e-3)
loss_function = torch.nn.MSELoss()

In [ ]:
train_dataset = torch.utils.data.TensorDataset(x_train_categ, x_train_numer, y_train_tensor)
val_dataset = torch.utils.data.TensorDataset(x_val_categ, x_val_numer, y_val_tensor)
test_dataset = torch.utils.data.TensorDataset(x_test_categ, x_test_numer, y_test_tensor)

batch_size = 16
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=batch_size)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size)

In [ ]:
num_epochs = 10
best_val_loss = float('inf')
best_model_state = None

In [ ]:
for epoch in range(num_epochs):
    # Training phase
    ft_transformer_model.train()
    train_loss = 0.0
    for batch_x_categ, batch_x_numer, batch_y in train_loader:
        batch_x_categ, batch_x_numer, batch_y = batch_x_categ.to(device), batch_x_numer.to(device), batch_y.to(device)

        optimizer.zero_grad()
        predictions = ft_transformer_model(batch_x_categ, batch_x_numer)
        loss = loss_function(predictions, batch_y)

        loss.backward()
        optimizer.step()

        train_loss += loss.item()

    # Validation phase
    ft_transformer_model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for batch_x_categ, batch_x_numer, batch_y in val_loader:
            batch_x_categ, batch_x_numer, batch_y = batch_x_categ.to(device), batch_x_numer.to(device), batch_y.to(device)

            predictions = ft_transformer_model(batch_x_categ, batch_x_numer)
            loss = loss_function(predictions, batch_y)

            val_loss += loss.item()

    # Save the best model based on validation loss
    val_loss /= len(val_loader)
    train_loss /= len(train_loader)

    print(f'Epoch {epoch+1}/{num_epochs}')
    print(f'Train Loss: {train_loss:.4f}, Validation Loss: {val_loss:.4f}')

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        best_model_state = ft_transformer_model.state_dict()

Epoch 1/10
Train Loss: 2.3159, Validation Loss: 1.2835
Epoch 2/10
Train Loss: 1.2172, Validation Loss: 1.2095
Epoch 3/10
Train Loss: 1.1914, Validation Loss: 1.1595
Epoch 4/10
Train Loss: 1.1752, Validation Loss: 1.1497
Epoch 5/10
Train Loss: 1.1573, Validation Loss: 1.1731
Epoch 6/10
Train Loss: 1.1418, Validation Loss: 1.1679
Epoch 7/10
Train Loss: 1.1291, Validation Loss: 1.1267
Epoch 8/10
Train Loss: 1.1212, Validation Loss: 1.1369
Epoch 9/10
Train Loss: 1.1110, Validation Loss: 1.0967
Epoch 10/10
Train Loss: 1.1068, Validation Loss: 1.1001


In [ ]:
import torch
import numpy as np
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

# Giả sử bạn đã có predictions và batch_y sau khi chạy qua mô hình
all_predictions = []
all_targets = []

ft_transformer_model.eval()
with torch.no_grad():
    for batch_x_categ, batch_x_numer, batch_y in test_loader:
        batch_x_categ, batch_x_numer, batch_y = batch_x_categ.to(device), batch_x_numer.to(device), batch_y.to(device)

        predictions = ft_transformer_model(batch_x_categ, batch_x_numer)
        all_predictions.append(predictions.cpu().numpy())
        all_targets.append(batch_y.cpu().numpy())

# Chuyển các mảng thành numpy arrays
all_predictions = np.concatenate(all_predictions)
all_targets = np.concatenate(all_targets)

# R² Score
r2 = r2_score(all_targets, all_predictions)
mse = mean_squared_error(all_targets, all_predictions)
rmse = np.sqrt(mse)
mae = mean_absolute_error(all_targets, all_predictions)
mape = np.mean(np.abs((all_targets - all_predictions) / all_targets)) * 100
mpe = np.mean((all_targets - all_predictions) / all_targets) * 100

print(f'R² Score: {r2:.4f}')
print(f'MSE: {mse:.4f}')
print(f'RMSE: {rmse:.4f}')
print(f'MAE: {mae:.4f}')
print(f'MAPE: {mape:.4f}%')
print(f'MPE: {mpe:.4f}%')


R² Score: 0.6718
MSE: 1.0988
RMSE: 1.0482
MAE: 0.7427
MAPE: 29.7597%
MPE: -17.4691%


In [ ]:
# Assuming 'ft_transformer_model' is your trained model
torch.save(ft_transformer_model.state_dict(), 'ft_transformer_model.pth')

In [ ]:
# Assuming you have the same model architecture
ft_transformer_model = FTTransformer(
    # ... your model parameters ...
)

ft_transformer_model.load_state_dict(torch.load('ft_transformer_model.pth'))
ft_transformer_model.eval()  # Set to evaluation mode

# **sample**

In [ ]:
import torch
from tab_transformer_pytorch import FTTransformer
import pandas as pd

# Cột phân loại (categorical) và số học (continuous)
categorical_columns = ['trangthai', 'gioitinh'] #, 'hedt', 'khoahoc']  # Các cột phân loại
numerical_columns = ['diem_hp', 'drl', 'dtbhk' , 'sotchk' , 'diem_tt', 'dtb_toankhoa', 'dtb_tichluy', 'sotc_tichluy', 'namsinh', 'namhoc', 'hocky']  # Các cột số học

# Chuẩn bị dữ liệu phân loại và số học
X_categ = X[categorical_columns].values
X_numer = X[numerical_columns].values

categorical_dims = []
for col in categorical_columns:
  categorical_dims.append(X[col].nunique())


# Chuyển thành tensor
x_categ = torch.tensor(X_categ, dtype=torch.long)
x_numer = torch.tensor(X_numer, dtype=torch.float32)

# Chuyển nhãn mục tiêu (y) thành tensor
y = torch.tensor(y.values.reshape(-1, 1), dtype=torch.float32)

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
import torch
from torch.utils.data import TensorDataset, DataLoader # Import TensorDataset and DataLoader
from tab_transformer_pytorch import FTTransformer
import pandas as pd

In [ ]:
ft_transformer_model = FTTransformer(
    categories=categorical_dims,
    num_continuous=len(numerical_columns),
    dim=8,
    dim_out=1,
    depth=6,
    heads=8,
    attn_dropout=0.1,
    ff_dropout=0.1
).to(device)  # Chuyển mô hình sang GPU nếu có

# Định nghĩa optimizer và hàm mất mát
optimizer = torch.optim.Adam(ft_transformer_model.parameters(), lr=1e-3)
loss_function = torch.nn.MSELoss()  # Hàm mất mát cho bài toán hồi quy

In [ ]:
dataset = TensorDataset(x_categ, x_numer, y)

# Create a DataLoader with a smaller batch size
batch_size = 16  # Adjust as needed
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

In [ ]:
num_epochs = 10
for epoch in range(num_epochs):
    ft_transformer_model.train()
    for batch_idx, (batch_x_categ, batch_x_numer, batch_y) in enumerate(dataloader):
        # Move batch data to device
        batch_x_categ, batch_x_numer, batch_y = batch_x_categ.to(device), batch_x_numer.to(device), batch_y.to(device)

        # Forward pass
        optimizer.zero_grad()
        predictions = ft_transformer_model(batch_x_categ, batch_x_numer)
        loss = loss_function(predictions, batch_y)

        # Backward pass
        loss.backward()
        optimizer.step()

        # Print loss periodically
        if batch_idx % 100 == 0:
            print(f'Epoch {epoch}, Batch {batch_idx}, Loss: {loss.item()}')

Epoch 0, Batch 0, Loss: 45.79073715209961
Epoch 0, Batch 100, Loss: 29.530460357666016
Epoch 0, Batch 200, Loss: 21.17450714111328
Epoch 0, Batch 300, Loss: 17.818452835083008
Epoch 0, Batch 400, Loss: 8.804121971130371
Epoch 0, Batch 500, Loss: 5.804176330566406
Epoch 0, Batch 600, Loss: 6.008052825927734
Epoch 0, Batch 700, Loss: 6.636524677276611
Epoch 0, Batch 800, Loss: 2.1480231285095215
Epoch 0, Batch 900, Loss: 4.031355381011963
Epoch 0, Batch 1000, Loss: 1.4368062019348145
Epoch 0, Batch 1100, Loss: 2.264559268951416
Epoch 0, Batch 1200, Loss: 1.907778024673462
Epoch 0, Batch 1300, Loss: 1.0195897817611694
Epoch 0, Batch 1400, Loss: 2.459305763244629
Epoch 0, Batch 1500, Loss: 1.3999546766281128
Epoch 0, Batch 1600, Loss: 0.7052663564682007
Epoch 0, Batch 1700, Loss: 1.0486403703689575
Epoch 0, Batch 1800, Loss: 1.8244050741195679
Epoch 0, Batch 1900, Loss: 3.5582704544067383
Epoch 0, Batch 2000, Loss: 1.3515138626098633
Epoch 0, Batch 2100, Loss: 0.5627960562705994
Epoch 0, B

KeyboardInterrupt: 